### ISSUE TITLE
Pakar IT box alignment problem

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/emasjidmy-landing#15]
![Screenshot 2024-03-21 at 11 55 11 PM](https://github.com/Dev4w4n/emasjidmy-landing/assets/11247162/a40d367a-8d2f-4bc3-914b-2eaafb244130)

**Comment by m-amirazmi** [comment]
Assign this to me

**Comment by m-amirazmi** [comment]
PR Created
[#20](https://github.com/Dev4w4n/emasjidmy-landing/pull/20)

Thank you.

**Comment by rohaizanr** [comment]
terima kasih
