### ISSUE TITLE
Mobile view error

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/emasjidmy-landing#17]
<img width="1003" alt="Screenshot 2024-03-23 at 2 35 42 AM" src="https://github.com/Dev4w4n/emasjidmy-landing/assets/11247162/138edf6f-184a-44b3-b9e6-805c88171284">

**Comment by m-amirazmi** [comment]
Assign this to me

**Comment by m-amirazmi** [comment]
[#19 ](https://github.com/Dev4w4n/emasjidmy-landing/pull/19)

PR created. Thank you

**Comment by rohaizanr** [comment]
terima kasih
