### ISSUE TITLE
Gambar bila share link https://www.e-masjid.my/

### ISSUE THREAD

**Issue by rohaizanr** [Dev4w4n/emasjidmy-landing#25]
Expected result:

1. Apabila link ini https://www.e-masjid.my/ di share di FB,twitter,discord,whatssap dan social media yang lain, gambar attach gambar dperhiasan seperti di bawah

![Screenshot 2024-03-28 at 10 17 00 PM](https://github.com/Dev4w4n/emasjidmy-landing/assets/11247162/5c4a5159-c5c8-453d-8396-44515353622f)

**Comment by m-amirazmi** [comment]
assign this to me

**Comment by rohaizanr** [comment]
> assign this to me

Estimate: 5 days. take your time :)

**Comment by m-amirazmi** [comment]
boleh bg link image sebab x silap yg ni, image nk host tempat lain kn?

**Comment by rohaizanr** [comment]
Boleh advise nak simpan kat mana?

Server kita internet tak laju

**Comment by m-amirazmi** [comment]
boleh letak mana2 yg boleh bg public access ke image. kalau boleh bg yg small size je. 

<img width="648" alt="image" src="https://github.com/Dev4w4n/emasjidmy-landing/assets/60350614/16d5963f-aad7-4afb-aef3-dbf9ec3fd492">

Sbb nnti image URL tu nk letak kt sini. lg mudah kalau ada image or file storage khas

**Comment by m-amirazmi** [comment]
kalau nk lg sng, letak je dlm public/images mcm image2 contributer tu

**Comment by rohaizanr** [comment]
https://cdn.e-masjid.my/images/emasjidmy-banner.png

**Comment by m-amirazmi** [comment]
PR Created
https://github.com/Dev4w4n/emasjidmy-landing/pull/26

**Comment by rohaizanr** [comment]
terima kasih. nicely done
